### ISSUE TITLE
...

### ISSUE THREAD

**Issue by iBlz** [smirea/reddit-place-bot#5]
yarn run v1.22.18
$ ts-node -T src/index.ts
/root/reddit-place-bot/src/BotPool.ts:92
                    const existingColor = RGB_MAP[hashRGB(r, g, b)]?.id;
                                                                    ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module.m._compile (/root/reddit-place-bot/node_modules/ts-node/src/index.ts:1455:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/root/reddit-place-bot/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/reddit-place-bot/src/index.ts:2:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by iBlz** [comment]
fix ur code

**Comment by smirea** [comment]
Works for me, it might be your nodejs version is out of date

feel free to put up a PR with a fix if not
